# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RatTrackiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, 10.0

  # Pods for RatTrackiOS
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'RatTrackiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RatTrackiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end


  # source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
end
